-- =============================================================================
-- Foster Care Compliance AI — 0002: caseworker-dispatched intake interviews
-- =============================================================================
-- Paste into the Supabase SQL editor and run ONCE. Tell the other person on the
-- shared database before you do: this is DDL. See docs/supabase-setup.md.
--
-- Design (CLAUDE.md §4a):
--
--   * The caseworker mints one session per household member. The session row
--     carries an unguessable link_token generated by Postgres (32 random bytes,
--     hex-encoded, 64 chars). The member opens /interview/<token> with no
--     account and no auth.uid().
--
--   * Because the member is anonymous, RLS keyed to auth.uid() would return
--     zero rows for them. We do NOT solve that with a permissive policy. The
--     anon role has NO direct access to any of these tables. It may only call
--     the SECURITY DEFINER functions at the bottom, each of which is scoped to
--     the single session whose link_token matches the argument and which has
--     not expired. The token is the capability.
--
--   * The caseworker side is ordinary RLS through the parent case:
--     cases.owner_user_id = auth.uid().
--
--   * interview_facts.accepted defaults false and is not a parameter of any
--     anon-callable function. The only path that sets it is a caseworker
--     UPDATE under RLS. "Everything is a draft until a human accepts it"
--     (CLAUDE.md §4a.3) is therefore enforced by the schema, not by the app.
--
--   * No column on any table can carry a score, rating, or characterization of
--     the subject (CLAUDE.md §4a.2). Do not add one.
--
-- CLAUDE.md hard boundary #3: synthetic subjects only. This schema has had no
-- privacy review and must never hold a real person's interview.
-- =============================================================================

-- gen_random_bytes lives in pgcrypto. Supabase installs it in the `extensions`
-- schema already; this is a no-op there and a safety net elsewhere.
create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- interview_sessions — one per household member per case
-- ----------------------------------------------------------------------------

create table if not exists public.interview_sessions (
  id            uuid        primary key default gen_random_uuid(),

  -- cases.id is TEXT (a docket like ICPC-2026-0247), never uuid.
  case_id       text        not null references public.cases (id) on delete cascade,

  subject_name  text        not null default '',
  subject_role  text        not null default '',
  script_id     text        not null,

  status        text        not null default 'pending'
                            check (status in ('pending', 'in_progress', 'complete', 'reviewed')),

  -- Minted by the database, never by the client. 32 bytes of randomness,
  -- hex-encoded. The check keeps anyone from inserting a short token by hand.
  link_token    text        not null unique
                            default encode(gen_random_bytes(32), 'hex')
                            check (length(link_token) >= 64),

  -- A link with no expiry is a standing capability; refuse to store one.
  expires_at    timestamptz not null default (now() + interval '7 days'),

  created_at    timestamptz not null default now(),
  completed_at  timestamptz
);

create index if not exists interview_sessions_case_idx
  on public.interview_sessions (case_id, created_at desc);

-- ----------------------------------------------------------------------------
-- interview_turns — the verbatim transcript, one row per utterance
-- ----------------------------------------------------------------------------
-- Persisted the moment each turn completes so a session lost at question 8
-- resumes rather than restarts. (session_id, turn_index) is unique so a
-- retried write is idempotent instead of duplicating a line of transcript.

create table if not exists public.interview_turns (
  id          uuid        primary key default gen_random_uuid(),
  session_id  uuid        not null references public.interview_sessions (id) on delete cascade,
  turn_index  integer     not null check (turn_index >= 0),
  speaker     text        not null check (speaker in ('agent', 'subject')),
  text        text        not null,
  started_at  timestamptz not null default now(),
  ended_at    timestamptz not null default now(),

  constraint interview_turns_unique_index unique (session_id, turn_index)
);

-- ----------------------------------------------------------------------------
-- interview_facts — extracted draft facts, each traceable to one utterance
-- ----------------------------------------------------------------------------

create table if not exists public.interview_facts (
  id           uuid        primary key default gen_random_uuid(),
  session_id   uuid        not null references public.interview_sessions (id) on delete cascade,
  fact_id      text        not null,
  value        text        not null,

  -- The exact words that produced the value. A fact a caseworker cannot trace
  -- is a fact they will ignore (CLAUDE.md §4a.4).
  verbatim     text        not null,
  block_id     text        not null,
  turn_index   integer     not null check (turn_index >= 0),

  accepted     boolean     not null default false,
  accepted_at  timestamptz,
  accepted_by  uuid        references auth.users (id) on delete set null,

  -- An accepted fact always records who and when; an unaccepted one never does.
  constraint interview_facts_acceptance_consistent check (
    (accepted = false and accepted_at is null and accepted_by is null)
    or
    (accepted = true and accepted_at is not null and accepted_by is not null)
  ),

  -- A clarification re-answering the same question replaces the draft value
  -- rather than stacking a second row.
  constraint interview_facts_unique_per_block unique (session_id, block_id, fact_id)
);

create index if not exists interview_facts_session_idx
  on public.interview_facts (session_id);

-- ----------------------------------------------------------------------------
-- Row-level security — caseworker side, through the parent case
-- ----------------------------------------------------------------------------

alter table public.interview_sessions enable row level security;
alter table public.interview_turns    enable row level security;
alter table public.interview_facts    enable row level security;

-- Supabase grants anon/authenticated on new public tables by default.
-- Anonymous callers get nothing here; they go through the functions below.
revoke all on table public.interview_sessions from anon;
revoke all on table public.interview_turns    from anon;
revoke all on table public.interview_facts    from anon;

-- sessions ------------------------------------------------------------------

drop policy if exists "caseworker reads own interview sessions" on public.interview_sessions;
create policy "caseworker reads own interview sessions"
  on public.interview_sessions for select
  using (exists (
    select 1 from public.cases c
    where c.id = interview_sessions.case_id and c.owner_user_id = auth.uid()
  ));

drop policy if exists "caseworker opens own interview sessions" on public.interview_sessions;
create policy "caseworker opens own interview sessions"
  on public.interview_sessions for insert
  with check (exists (
    select 1 from public.cases c
    where c.id = interview_sessions.case_id and c.owner_user_id = auth.uid()
  ));

drop policy if exists "caseworker updates own interview sessions" on public.interview_sessions;
create policy "caseworker updates own interview sessions"
  on public.interview_sessions for update
  using (exists (
    select 1 from public.cases c
    where c.id = interview_sessions.case_id and c.owner_user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.cases c
    where c.id = interview_sessions.case_id and c.owner_user_id = auth.uid()
  ));

drop policy if exists "caseworker deletes own interview sessions" on public.interview_sessions;
create policy "caseworker deletes own interview sessions"
  on public.interview_sessions for delete
  using (exists (
    select 1 from public.cases c
    where c.id = interview_sessions.case_id and c.owner_user_id = auth.uid()
  ));

-- turns ---------------------------------------------------------------------
-- The caseworker reads the transcript and may seed one (demo fixtures) or
-- remove one with the session. They do not edit a subject's words: no update.

drop policy if exists "caseworker reads own interview turns" on public.interview_turns;
create policy "caseworker reads own interview turns"
  on public.interview_turns for select
  using (exists (
    select 1
    from public.interview_sessions s
    join public.cases c on c.id = s.case_id
    where s.id = interview_turns.session_id and c.owner_user_id = auth.uid()
  ));

drop policy if exists "caseworker inserts own interview turns" on public.interview_turns;
create policy "caseworker inserts own interview turns"
  on public.interview_turns for insert
  with check (exists (
    select 1
    from public.interview_sessions s
    join public.cases c on c.id = s.case_id
    where s.id = interview_turns.session_id and c.owner_user_id = auth.uid()
  ));

drop policy if exists "caseworker deletes own interview turns" on public.interview_turns;
create policy "caseworker deletes own interview turns"
  on public.interview_turns for delete
  using (exists (
    select 1
    from public.interview_sessions s
    join public.cases c on c.id = s.case_id
    where s.id = interview_turns.session_id and c.owner_user_id = auth.uid()
  ));

-- facts ---------------------------------------------------------------------

drop policy if exists "caseworker reads own interview facts" on public.interview_facts;
create policy "caseworker reads own interview facts"
  on public.interview_facts for select
  using (exists (
    select 1
    from public.interview_sessions s
    join public.cases c on c.id = s.case_id
    where s.id = interview_facts.session_id and c.owner_user_id = auth.uid()
  ));

drop policy if exists "caseworker inserts own interview facts" on public.interview_facts;
create policy "caseworker inserts own interview facts"
  on public.interview_facts for insert
  with check (exists (
    select 1
    from public.interview_sessions s
    join public.cases c on c.id = s.case_id
    where s.id = interview_facts.session_id and c.owner_user_id = auth.uid()
  ));

-- Accept / Edit. The acceptance check constraint above forces accepted_by to
-- be set when accepted flips true; the with-check below forces it to be the
-- signed-in caseworker rather than an arbitrary uuid.
drop policy if exists "caseworker updates own interview facts" on public.interview_facts;
create policy "caseworker updates own interview facts"
  on public.interview_facts for update
  using (exists (
    select 1
    from public.interview_sessions s
    join public.cases c on c.id = s.case_id
    where s.id = interview_facts.session_id and c.owner_user_id = auth.uid()
  ))
  with check (
    (accepted_by is null or accepted_by = auth.uid())
    and exists (
      select 1
      from public.interview_sessions s
      join public.cases c on c.id = s.case_id
      where s.id = interview_facts.session_id and c.owner_user_id = auth.uid()
    )
  );

drop policy if exists "caseworker deletes own interview facts" on public.interview_facts;
create policy "caseworker deletes own interview facts"
  on public.interview_facts for delete
  using (exists (
    select 1
    from public.interview_sessions s
    join public.cases c on c.id = s.case_id
    where s.id = interview_facts.session_id and c.owner_user_id = auth.uid()
  ));

-- ----------------------------------------------------------------------------
-- Anonymous access — token-scoped SECURITY DEFINER functions
-- ----------------------------------------------------------------------------
-- These run as the function owner (postgres in the SQL editor) and therefore
-- bypass RLS. Every one of them:
--   * resolves exactly one session by link_token,
--   * refuses if the link is expired,
--   * refuses writes once the session is complete or reviewed,
--   * never accepts a session id, case id, or `accepted` flag from the caller.
-- There is no way to enumerate sessions or reach another session's rows.

-- Internal helper: the live session for a token, or null. Not granted to anon.
create or replace function public.interview_session_for_token(p_token text)
returns public.interview_sessions
language sql
stable
security definer
set search_path = public
as $$
  select s.*
  from public.interview_sessions s
  where s.link_token = p_token
    and s.expires_at > now()
  limit 1;
$$;

revoke all on function public.interview_session_for_token(text) from public, anon, authenticated;

-- 1. Read the session behind a link. Returns zero rows for an unknown or
--    expired token, so the page renders "This link is no longer valid".
--    Deliberately omits link_token and case_id: the subject has no case
--    visibility and does not need to see the capability they already hold.
create or replace function public.get_interview_by_token(p_token text)
returns table (
  id            uuid,
  subject_name  text,
  subject_role  text,
  script_id     text,
  status        text,
  expires_at    timestamptz,
  completed_at  timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select s.id, s.subject_name, s.subject_role, s.script_id, s.status,
         s.expires_at, s.completed_at
  from public.interview_sessions s
  where s.link_token = p_token
    and s.expires_at > now();
$$;

-- 2. The transcript so far, so an interrupted session resumes at the right
--    question instead of restarting. Empty for unknown/expired tokens.
create or replace function public.get_interview_turns_by_token(p_token text)
returns table (
  turn_index  integer,
  speaker     text,
  text        text,
  started_at  timestamptz,
  ended_at    timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select t.turn_index, t.speaker, t.text, t.started_at, t.ended_at
  from public.interview_turns t
  join public.interview_sessions s on s.id = t.session_id
  where s.link_token = p_token
    and s.expires_at > now()
  order by t.turn_index;
$$;

-- 3. Persist one turn. Idempotent on (session, turn_index). Moves a pending
--    session to in_progress on the first write.
create or replace function public.append_interview_turn(
  p_token       text,
  p_turn_index  integer,
  p_speaker     text,
  p_text        text,
  p_started_at  timestamptz default now(),
  p_ended_at    timestamptz default now()
)
returns uuid
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_session public.interview_sessions;
  v_turn_id uuid;
begin
  v_session := public.interview_session_for_token(p_token);
  if v_session.id is null then
    raise exception 'interview link is invalid or expired' using errcode = 'P0002';
  end if;
  if v_session.status not in ('pending', 'in_progress') then
    raise exception 'interview session is closed' using errcode = 'P0003';
  end if;

  insert into public.interview_turns
    (session_id, turn_index, speaker, text, started_at, ended_at)
  values
    (v_session.id, p_turn_index, p_speaker, p_text,
     coalesce(p_started_at, now()), coalesce(p_ended_at, now()))
  on conflict (session_id, turn_index) do update
    set speaker    = excluded.speaker,
        text       = excluded.text,
        started_at = excluded.started_at,
        ended_at   = excluded.ended_at
  returning id into v_turn_id;

  if v_session.status = 'pending' then
    update public.interview_sessions
      set status = 'in_progress'
      where id = v_session.id;
  end if;

  return v_turn_id;
end;
$$;

-- 4. Record one extracted draft fact. Never accepted: `accepted` is not a
--    parameter, and an already-accepted row is never overwritten.
create or replace function public.record_interview_fact(
  p_token       text,
  p_fact_id     text,
  p_value       text,
  p_verbatim    text,
  p_block_id    text,
  p_turn_index  integer
)
returns uuid
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_session public.interview_sessions;
  v_fact_id uuid;
begin
  v_session := public.interview_session_for_token(p_token);
  if v_session.id is null then
    raise exception 'interview link is invalid or expired' using errcode = 'P0002';
  end if;
  if v_session.status not in ('pending', 'in_progress') then
    raise exception 'interview session is closed' using errcode = 'P0003';
  end if;

  insert into public.interview_facts
    (session_id, fact_id, value, verbatim, block_id, turn_index)
  values
    (v_session.id, p_fact_id, p_value, p_verbatim, p_block_id, p_turn_index)
  on conflict (session_id, block_id, fact_id) do update
    set value      = excluded.value,
        verbatim   = excluded.verbatim,
        turn_index = excluded.turn_index
    where public.interview_facts.accepted = false
  returning id into v_fact_id;

  -- on conflict ... where <false> returns no row; that means the caseworker
  -- has already accepted this fact and the draft must not move under them.
  if v_fact_id is null then
    select id into v_fact_id
    from public.interview_facts
    where session_id = v_session.id and block_id = p_block_id and fact_id = p_fact_id;
  end if;

  return v_fact_id;
end;
$$;

-- 5. Close the session. The subject cannot reopen it, cannot mark it
--    reviewed, and cannot touch any other status.
create or replace function public.complete_interview_by_token(p_token text)
returns boolean
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_session public.interview_sessions;
begin
  v_session := public.interview_session_for_token(p_token);
  if v_session.id is null then
    raise exception 'interview link is invalid or expired' using errcode = 'P0002';
  end if;
  if v_session.status = 'complete' then
    return true;
  end if;
  if v_session.status <> 'in_progress' and v_session.status <> 'pending' then
    raise exception 'interview session is closed' using errcode = 'P0003';
  end if;

  update public.interview_sessions
    set status = 'complete', completed_at = now()
    where id = v_session.id;
  return true;
end;
$$;

-- ----------------------------------------------------------------------------
-- Grants — anon (and a signed-in caseworker who opens the link) may call the
-- token-scoped functions and nothing else.
-- ----------------------------------------------------------------------------

revoke all on function public.get_interview_by_token(text)                                              from public;
revoke all on function public.get_interview_turns_by_token(text)                                        from public;
revoke all on function public.append_interview_turn(text, integer, text, text, timestamptz, timestamptz) from public;
revoke all on function public.record_interview_fact(text, text, text, text, text, integer)              from public;
revoke all on function public.complete_interview_by_token(text)                                         from public;

grant execute on function public.get_interview_by_token(text)                                              to anon, authenticated;
grant execute on function public.get_interview_turns_by_token(text)                                        to anon, authenticated;
grant execute on function public.append_interview_turn(text, integer, text, text, timestamptz, timestamptz) to anon, authenticated;
grant execute on function public.record_interview_fact(text, text, text, text, text, integer)              to anon, authenticated;
grant execute on function public.complete_interview_by_token(text)                                         to anon, authenticated;
